function(func arg)
    if(DEFINED arg)
        message("function's arg = ${arg}")
    else()
        message("function's arg is not defined")
    endif()
endfunction()

macro(macr arg)
    if(DEFINED arg)
        message("macro's arg = ${arg}")
    else()
        message("macro's arg is not defined")
    endif()
endmacro()

set(myArgu "myArgument")
func(${myArgu})
func(myArgu)
func(noArg)
func("myArgu")
func("noArg")
macr(${myArgu})
macr(myArgu)
macr(noArg)
macr("myArgu")
macr("noArg")